### PR TITLE
Update rails rake task to run rails4.2 test suite

### PR DESCRIPTION
**Pull request by summera**
@apotonick This will run the rails4.2 test suite with `rake rails`. However, when run with `bundle exec rake rails` it breaks because the Gemfile at the root of the gem is loaded instead of the Gemfile in the `test/rails4.2` directory. It will work when running `BUNDLE_GEMFILE=test/rails4.2/Gemfile bundle exec rake rails`. 

Trying to find a workaround so that this is not necessary. Any ideas?

### CODE REVIEW

**Comment by apotonick** [comment]
Thanks man!! But... where do you add the new task to the existing default one?

**Comment by summera** [comment]
Didn't add it in yet. Wanted to get your thoughts on the `bundle exec` issue before doing so.

**Comment by apotonick** [comment]
I think we have to make the second rake task "chdir" into `test/rails4.2` and run `rake` there. That's basically what I do now.

**Comment by summera** [comment]
@apotonick working locally. Breaking on travis because we aren't bundle installing in the rails 4.2 directory https://travis-ci.org/apotonick/cells/jobs/65027019

**Comment by seuros** [comment]
Closing Stale PR

**Pull request closed without merging**
