### PR TITLE
Getting the ball rolling for 5.0

### PR DESCRIPTION
**Pull request by george-carlin**
We've talked about some ideas for Cell 5.0. It feels overdue. I'm still not sure what the exact plan is, but I figured I'd get started based on what I do know:

1. Removed 'Cell::Concept', and related inflection/constantizing magic that guesses constant names from strings.
2. Removed the stuff that's marked as deprecated or with comments that say 'remove in 5.0'.

~~I also noticed when I ran `rake test` on `master` that a bunch of the tests were failing. Seems that the tests are expecting strings with no newline on the end, but the cells render a string with a newline. Not sure why this is broken, because it seems to pass on CI as-is. Could it be caused by a version update to `ERB`? I haven't investigated thoroughly, but I "fixed" the tests in 4a5b484 just so I could get a green suite locally. This may need reverting.~~ fixed by #452 

This PR targets `master`, but if it accepted it should probably be put on a new branch entirely until 5.0 is ready to roll.

You'll notice that the PR doesn't really add anything, it just removes deprecated stuff. Are there any planned new features for 5.0, or will it mainly be cleanup and refactoring and removal of deprecated stuff?

### CODE REVIEW

**Comment by georgemillo** [comment]
We've also talked about merging `Cell::ViewModel` and `Trailblazer::Cell` into a single class. This would also mean merging `cells` and `trailblazer-cells`, which I think only makes sense as it's confusing to have two gems, and `trailblazer-cells` is only a [single file](https://github.com/trailblazer/trailblazer-cells/blob/master/lib/trailblazer/cell.rb) with less than 50 LOC.

If these two classes are merged, will the new class be called `Cell::ViewModel` or `Trailblazer::Cell`? I think it makes sense to stick with `Cell::ViewModel` and consign `Trailblazer::Cell` to the dustbin. This follows the pattern set by other TRB gems - e.g. `disposable` and `reform` use classes called `Disposable:*` and `Reform::*`, not `Trailblazer::Disposable` and `Trailblazer::Reform`.

Or perhaps it would reduce confusion by scrapping both old names, and using a new constant name for 5.0? `Cells::Cell`? `Cells::ViewModel`? `Cell::Model`? `Cell::View`? (I like the idea of using `Cells` instead of `Cell` as the outermost namespace as it's more conventional to have the top-level namespace be the same as the name of the gem.)

Whatever the case, if one or both of the existing classes is going to be removed I think a new `4.X` version should be released that includes deprecation warnings for anyone trying to use the outdated class.

**Comment by georgemillo** [comment]
aaaaand it looks like my "fix" for the "broken" tests ended up breaking them on CI. I'll investigate what the source of the problem is.

**Comment by schorsch** [comment]
Great to see you starting to groom. Is there any other place(ticket) dedicated to some major code removal/cleanup? 

On my list:

* remove cell(:name) calls in favour of MyCellClass.()    
* do we really need a 'show' method, when we use def call() anyway?
* above could also simplify caching, which could need some love in getting the cache-key or deleting a key base on the cells current model 
* remove :collection magic rendering as it leads to ugly code instead of simply opening a table and use simply each + render call in a template 
* allow explizit params for a cells call() method as an options hash is hard to track, and sometimes a dont have a model so the first arg is nil
* dont assume the cells base folder and always set it in initializer or base class
* maybe there is away i can build my ow base class and include only some modules to achive cleaner classes like mentioned above

**Comment by georgemillo** [comment]
> remove cell(:name) calls in favour of MyCellClass.()

If you're talking about passing a string to the `cell` helper (e.g. `cell('song')` to render `SongCell`), my commits above already remove this. But you can still pass the constant to the `cell` helper directly: `cell(SongCell)`. Why do you want to remove this? If you're using cells with rails, `SongCell.()` can't be used as a drop-in replacement for `cell(SongCell)`, because the `cell` helper also passes in the `controller` context (so that the cell can access things like routes.)

> remove :collection magic rendering as it leads to ugly code instead of simply opening a table/list and use my_objects.each + render call in a template

What's wrong with `collection`? I use this all the time. `cell(SongCell, collection: songs)` is much cleaner and simpler than `songs.each { |song| SongCell.() }` if you ask me, plus the `Collection` class has extra functionality e.g. `join`.

> allow explizit params for a cells call() method, as an options hash is hard to track, and sometimes i dont have a model so the first arg is nil

Not sure what you mean by "explicit" params - what's your suggested syntax for this? I opened a PR for an `option` class method at #449 - is this the kind of thing you're talking about?

**Comment by georgemillo** [comment]
I also think that once Cells 5 is released, it may be time to bump the version of all the 'support' gems (cells-rails, cells-erb, cells-slim etc) to 1.0.0. Most of them are currently on versions like `0.0.x` which implies major instability, and is sure to discourage people from using cells in their projects. A major version bump of the core gem is a good opportunity to "lock down" the support gems with a stable API.

**Comment by schorsch** [comment]
> remove cell(:name) calls in favour of MyCellClass.()

I dont use any link_to magic anymore and voted for plain links like %a{href:"/my/area/{model.id"}. Same goes for form_for & field_helpers, where plain HAML is a decent fit and much more stable between rails upgrades (e.g. renaming of form/field-ids where your js depend on). So i tried to decouple my views from rails(helpers) as much as possible, but of course i do understand the necessity to keep it around. The cell() helper to wrap the rails controller context could f.ex be moved to the cell-rails gem. 


>  :collection magic rendering 

The usage might be a personal taste. When not using cell() it does impose a call like MyCell.(nil, collection: xy). Maybe there is a chance to outsource it into a module, so one can opt-in to use it and the default cell() wrapper has it already included.

> explizit params

Throwing whatever into the options parameter is convenient but gets really dirty when you start passing them from one cell to another, where each cell requires a different part of them. Atm. i try to comment the required options as much as possible or raise if something is missing. Rails 5.1 move to ActionParams (which also has its positive effects) and the habit to add controller/action names to the request params lead me to avoid juggling with params and just use&pass the required parts: MyCell.(an_object, user: current_user).
I could imagine a structure like:

```ruby
class MyCell
   include Cells::Render
   extend Cells::Cache
   include Maybe::SomeRailsNumberHelper

 # The params can be commented, used for lookup by autocompletes in IDE's,
 # transparently set defaults and use 'jump-to-definition' in IDE
 # @param [MyModel] model a single product
 # @param [User] user product owner
 # @return ..
  def call(model, user, another='default')
    # do stuff
    render
  end
end

# VS my current approach where i have no chance to directly comment e.g. the 
# model type (+ options hash inject in by my own base class)
  class Index < ApplicationCell
    include PaginationHelper
    
   # no params needed .. half a year later .. which params are needed? What's the model kind? 
    def show
      @scope  = options[:scope] || :my
      @filter = options[:filter] # required
      @org    = options[:org] if options[:org]
      render
    end
  end

``` 

For me it boils down to having a slim(fast) 'rendering' toolbox. I can give some more insights on my usage and how i moved from ActionView -> cell(:xy) -> MyCell.() and using Rails now mostly for controller/routes/models. But dont know if this ticket is a good fit for it.
Result can be seen https://app.reimbursement.info/icds/F10-F19 where f.ex. each box in the body is cell

**Comment by georgemillo** [comment]
Hmmm, I suppose when it comes to rendering collections, it is a bit strange using the "magic" option `:collection`. (It also means that you can't have a normal option called `collection`, although I doubt that trips many people up.)

Alternative idea: render a collection by calling a class method on the cell instead?

So e.g. the syntax could be:

```ruby
MyCell.for_collection(x)

**Comment by georgemillo** [comment]
Hmmm, I suppose when it comes to rendering collections, it is a bit strange using the "magic" option `:collection`. (It also means that you can't have a normal option called `collection`, although I doubt that trips many people up.)

Alternative idea: render a collection by calling a class method on the cell instead?

So e.g. the syntax could be:

```ruby
MyCell.for_collection(x)
# instead of
MyCell.(nil, collection: x)
```

... which does feel a bit cleaner to me. If we're going to keep the `cell` helper around, then a second helper called `collection` could also be added which calls the `for_collection` method instead of `MyCell.call`.

I'll write some more later about context/routes/links and param comments later when I have the time.

**Comment by georgemillo** [comment]
Another possible change for 5.0: remove dependency on the `uber` gem as I believe it's now deprecated?

**Comment by Startouf** [comment]
> it may be time to bump the version of all the 'support' gems 

Note regarding cells-erb : 0.1.0 has a somewhat breaking change where `concat` no longer works, could be a pain for all the users who have custom helpers (bootstrap, foundation) and were relying on concat. Not entirely sure it's a good decision to bumb this one if it was already there.

Furthermore, I though those gems had to be added manually to better adapt to developer styles ?

**Pull request closed without merging**
