### PR TITLE
add extra example to README

### PR DESCRIPTION
**Pull request by georgemillo**

### CODE REVIEW

**Comment by seanfcarroll** [comment]
It also works for concepts

```
<%= concept(UserWord::Cell,sentence_words.first) %>
```

**Comment by georgemillo** [comment]
I think the plan is to remove concepts in Cells 5?

**Comment by apotonick** [comment]
Yeah! In Cells 5, there is only the `Trailblazer::Cell` style, and it'll *finally* be called "cell", again.

**Comment by apotonick** [comment]
Actually, we should mark that the constant way is the new default, @georgemillo!!!

**Comment by georgemillo** [comment]
@apotonick we've talked about this before, but to confirm, is the plan to get rid of `Cell::ViewModel` and just use `Trailblazer::Cell` for everything? Or is the `C::VM > T::C` hierarchy gonna be kept?

If it's the former, is the plan to merge `trailblazer-cells` and `cells` into a single gem?

**Comment by apotonick** [comment]
I think they will be merged? Not sure about the inheritance hierarchy, though.

There's no point in dragging around 3 different styles forever :blush: (my bad!).

**Comment by apotonick** [comment]
Actually @georgemillo it's probably a good time to start talking about Cells 5? We should reactivate @timoschilling for this.

**Pull request merged**
